"""schema inicial

Revision ID: 88f2c95541a9
Revises:
Create Date: 2026-09-14 05:37:35.806341+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "88f2c95541a9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_history",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("position_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("document_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("classifier", sa.String(length=48), nullable=False),
        sa.Column("classifier_version", sa.String(length=32), nullable=False),
        sa.Column(
            "outcome",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classification_history_opportunity_id"),
        "classification_history",
        ["opportunity_id"],
        unique=False,
    )
    op.create_table(
        "errors",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("document_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_errors_created_at"), "errors", ["created_at"], unique=False)
    op.create_index(op.f("ix_errors_run_id"), "errors", ["run_id"], unique=False)
    op.create_index(op.f("ix_errors_source_id"), "errors", ["source_id"], unique=False)
    op.create_table(
        "extraction_results",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_hash", "prompt_version", "model", "model_version", name="uq_extraction_cache"
        ),
    )
    op.create_index(
        op.f("ix_extraction_results_document_hash"),
        "extraction_results",
        ["document_hash"],
        unique=False,
    )
    op.create_table(
        "monitor_runs",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sources_attempted", sa.Integer(), nullable=False),
        sa.Column("sources_successful", sa.Integer(), nullable=False),
        sa.Column("sources_failed", sa.Integer(), nullable=False),
        sa.Column("sources_skipped", sa.Integer(), nullable=False),
        sa.Column("documents_discovered", sa.Integer(), nullable=False),
        sa.Column("documents_changed", sa.Integer(), nullable=False),
        sa.Column("opportunities_created", sa.Integer(), nullable=False),
        sa.Column("opportunities_updated", sa.Integer(), nullable=False),
        sa.Column("notifications_sent", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_runs_started_at"), "monitor_runs", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_monitor_runs_status"), "monitor_runs", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_category"), "notifications", ["category"], unique=False)
    op.create_index(
        op.f("ix_notifications_idempotency_key"), "notifications", ["idempotency_key"], unique=True
    )
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("dedup_key", sa.String(length=128), nullable=False),
        sa.Column("institution", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("edital_number", sa.String(length=64), nullable=True),
        sa.Column("employment_type", sa.String(length=24), nullable=False),
        sa.Column("employment_regime", sa.String(length=64), nullable=True),
        sa.Column("organizing_board", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("registration_start", sa.Date(), nullable=True),
        sa.Column("registration_deadline", sa.Date(), nullable=True),
        sa.Column("exam_date", sa.Date(), nullable=True),
        sa.Column("exam_location", sa.Text(), nullable=True),
        sa.Column("application_fee", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("fee_exemption", sa.Text(), nullable=True),
        sa.Column("fee_exemption_deadline", sa.Date(), nullable=True),
        sa.Column("payment_deadline", sa.Date(), nullable=True),
        sa.Column(
            "selection_stages",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("validity", sa.Text(), nullable=True),
        sa.Column("official_edital_url", sa.String(length=1024), nullable=True),
        sa.Column("official_institution_url", sa.String(length=1024), nullable=True),
        sa.Column("official_application_url", sa.String(length=1024), nullable=True),
        sa.Column("organizing_board_url", sa.String(length=1024), nullable=True),
        sa.Column("best_trust_level", sa.Integer(), nullable=False),
        sa.Column("best_authority", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("workload_classification", sa.String(length=16), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "conflicts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunities_dedup_key"), "opportunities", ["dedup_key"], unique=True)
    op.create_index(op.f("ix_opportunities_eligible"), "opportunities", ["eligible"], unique=False)
    op.create_index(
        op.f("ix_opportunities_needs_review"), "opportunities", ["needs_review"], unique=False
    )
    op.create_index(op.f("ix_opportunities_score"), "opportunities", ["score"], unique=False)
    op.create_index(op.f("ix_opportunities_status"), "opportunities", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("institution", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("official", sa.Boolean(), nullable=False),
        sa.Column("trust_level", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("discovery_method", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("trust_status", sa.String(length=16), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("discovered_from", sa.Text(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_events_created_at"), "system_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_system_events_kind"), "system_events", ["kind"], unique=False)
    op.create_index(op.f("ix_system_events_run_id"), "system_events", ["run_id"], unique=False)
    op.create_table(
        "deadlines",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "kind", name="uq_deadline_kind"),
    )
    op.create_index(op.f("ix_deadlines_due_date"), "deadlines", ["due_date"], unique=False)
    op.create_index(
        op.f("ix_deadlines_opportunity_id"), "deadlines", ["opportunity_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("canonical_url", sa.String(length=1024), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=32), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_version_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("processing_state", sa.String(length=16), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_documents_canonical_url"), "documents", ["canonical_url"], unique=False
    )
    op.create_index(
        op.f("ix_documents_processing_state"), "documents", ["processing_state"], unique=False
    )
    op.create_index(op.f("ix_documents_source_id"), "documents", ["source_id"], unique=False)
    op.create_table(
        "opportunity_versions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("document_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("document_version_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "version", name="uq_opportunity_version"),
    )
    op.create_index(
        op.f("ix_opportunity_versions_opportunity_id"),
        "opportunity_versions",
        ["opportunity_id"],
        unique=False,
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("education", sa.String(length=32), nullable=True),
        sa.Column("qualification_category", sa.String(length=48), nullable=False),
        sa.Column(
            "additional_qualifications",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("vacancies", sa.Integer(), nullable=True),
        sa.Column("reserve_list", sa.Boolean(), nullable=True),
        sa.Column("reserve_count", sa.Integer(), nullable=True),
        sa.Column("assignment_location", sa.Text(), nullable=True),
        sa.Column(
            "possible_assignment_locations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("assignment_confirmed", sa.Boolean(), nullable=False),
        sa.Column("salary", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("benefits", sa.Text(), nullable=True),
        sa.Column("weekly_workload", sa.Float(), nullable=True),
        sa.Column("daily_workload", sa.Float(), nullable=True),
        sa.Column("workload_classification", sa.String(length=16), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("primary_alert", sa.Boolean(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "slug", name="uq_position_slug"),
    )
    op.create_index(op.f("ix_positions_eligible"), "positions", ["eligible"], unique=False)
    op.create_index(
        op.f("ix_positions_opportunity_id"), "positions", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_positions_slug"), "positions", ["slug"], unique=False)
    op.create_table(
        "source_health",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("total_successes", sa.Integer(), nullable=False),
        sa.Column("parser_attempts", sa.Integer(), nullable=False),
        sa.Column("parser_successes", sa.Integer(), nullable=False),
        sa.Column("last_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_response_ms", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("documents_last_run", sa.Integer(), nullable=True),
        sa.Column("documents_median", sa.Float(), nullable=True),
        sa.Column(
            "document_history",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("open_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("issue_number", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "source_runs",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response_ms", sa.Integer(), nullable=True),
        sa.Column("documents_discovered", sa.Integer(), nullable=False),
        sa.Column("documents_new", sa.Integer(), nullable=False),
        sa.Column("documents_changed", sa.Integer(), nullable=False),
        sa.Column("drift_detected", sa.Boolean(), nullable=False),
        sa.Column("recovery_method", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["monitor_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_id", name="uq_source_run"),
    )
    op.create_index(op.f("ix_source_runs_run_id"), "source_runs", ["run_id"], unique=False)
    op.create_index(op.f("ix_source_runs_source_id"), "source_runs", ["source_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("document_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("text_status", sa.String(length=24), nullable=False),
        sa.Column("extraction_method", sa.String(length=32), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("semantic_version", sa.String(length=64), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "content_hash", name="uq_document_version"),
    )
    op.create_index(
        op.f("ix_document_versions_content_hash"),
        "document_versions",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_table(
        "raw_snapshots",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("document_version_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_snapshots")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_content_hash"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_source_runs_source_id"), table_name="source_runs")
    op.drop_index(op.f("ix_source_runs_run_id"), table_name="source_runs")
    op.drop_table("source_runs")
    op.drop_table("source_health")
    op.drop_index(op.f("ix_positions_slug"), table_name="positions")
    op.drop_index(op.f("ix_positions_opportunity_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_eligible"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_opportunity_versions_opportunity_id"), table_name="opportunity_versions")
    op.drop_table("opportunity_versions")
    op.drop_index(op.f("ix_documents_source_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_processing_state"), table_name="documents")
    op.drop_index(op.f("ix_documents_canonical_url"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_deadlines_opportunity_id"), table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_due_date"), table_name="deadlines")
    op.drop_table("deadlines")
    op.drop_index(op.f("ix_system_events_run_id"), table_name="system_events")
    op.drop_index(op.f("ix_system_events_kind"), table_name="system_events")
    op.drop_index(op.f("ix_system_events_created_at"), table_name="system_events")
    op.drop_table("system_events")
    op.drop_table("sources")
    op.drop_index(op.f("ix_opportunities_status"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_score"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_needs_review"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_eligible"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_dedup_key"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_idempotency_key"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_category"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_monitor_runs_status"), table_name="monitor_runs")
    op.drop_index(op.f("ix_monitor_runs_started_at"), table_name="monitor_runs")
    op.drop_table("monitor_runs")
    op.drop_index(op.f("ix_extraction_results_document_hash"), table_name="extraction_results")
    op.drop_table("extraction_results")
    op.drop_index(op.f("ix_errors_source_id"), table_name="errors")
    op.drop_index(op.f("ix_errors_run_id"), table_name="errors")
    op.drop_index(op.f("ix_errors_created_at"), table_name="errors")
    op.drop_table("errors")
    op.drop_index(
        op.f("ix_classification_history_opportunity_id"), table_name="classification_history"
    )
    op.drop_table("classification_history")
    # ### end Alembic commands ###
